package com.zhiluniao.jobs.model.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;
import lombok.ToString;
@Data
@Entity
@ToString
@Table(name = "collect_task")
public class CollectTaskEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_task.id
     *
     * @mbg.generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;
    
    @Column(name = "date")
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_task.remote_uri
     *
     * @mbg.generated
     */
    @Column(name = "remote_uri")
    private String remoteUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_task.local_uri
     *
     * @mbg.generated
     */
    @Column(name = "local_uri")
    private String localUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_task.is_download
     *
     * @mbg.generated
     */
    @Column(name = "is_download")
    private String isDownload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_task.is_load
     *
     * @mbg.generated
     */
    @Column(name = "is_load")
    private String isLoad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_task.create_time
     *
     * @mbg.generated
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_task.id
     *
     * @return the value of collect_task.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_task.id
     *
     * @param id the value for collect_task.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_task.remote_uri
     *
     * @return the value of collect_task.remote_uri
     *
     * @mbg.generated
     */
    public String getRemoteUri() {
        return remoteUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_task.remote_uri
     *
     * @param remoteUri the value for collect_task.remote_uri
     *
     * @mbg.generated
     */
    public void setRemoteUri(String remoteUri) {
        this.remoteUri = remoteUri == null ? null : remoteUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_task.local_uri
     *
     * @return the value of collect_task.local_uri
     *
     * @mbg.generated
     */
    public String getLocalUri() {
        return localUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_task.local_uri
     *
     * @param localUri the value for collect_task.local_uri
     *
     * @mbg.generated
     */
    public void setLocalUri(String localUri) {
        this.localUri = localUri == null ? null : localUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_task.is_download
     *
     * @return the value of collect_task.is_download
     *
     * @mbg.generated
     */
    public String getIsDownload() {
        return isDownload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_task.is_download
     *
     * @param isDownload the value for collect_task.is_download
     *
     * @mbg.generated
     */
    public void setIsDownload(String isDownload) {
        this.isDownload = isDownload == null ? null : isDownload.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_task.is_load
     *
     * @return the value of collect_task.is_load
     *
     * @mbg.generated
     */
    public String getIsLoad() {
        return isLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_task.is_load
     *
     * @param isLoad the value for collect_task.is_load
     *
     * @mbg.generated
     */
    public void setIsLoad(String isLoad) {
        this.isLoad = isLoad == null ? null : isLoad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_task.create_time
     *
     * @return the value of collect_task.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_task.create_time
     *
     * @param createTime the value for collect_task.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}